#!/bin/bash

GROSSDIR=`pwd`
if [ -z "$BOSSDIR" ]; then
  echo "Run bossenv.sh first"
  exit 1
fi


cat >grossenv.sh <<EOF
. ${BOSSDIR}/bossenv.sh
export GROSSDIR=$GROSSDIR
export PATH=\${PATH}:\${GROSSDIR}/bin
EOF

cat >grossenv.csh <<EOF
source ${BOSSDIR}/bossenv.csh
setenv GROSSDIR ${GROSSDIR}
setenv PATH \${PATH}:\${GROSSDIR}/bin
EOF

. grossenv.sh
