CPP = g++
CPPFLAGS = -g -ansi
#CPPFLAGS = -ansi
OFLAG = -o
.SUFFIXES : .o .cpp
.cpp.o :
	$(CPP) $(CPPFLAGS) $(INCLUDES) -c $<
.cc.o :
	$(CPP) $(CPPFLAGS) $(INCLUDES) -c $<

#BOSS stuff (including Classad, MySQL)
TOPDIR=${BOSSDIR}
CMSDIR=${CMS_PATH}
BINDIR=$(TOPDIR)/bin
CLADINC=$(TOPDIR)/ClassAdLite/include
BOSSINC=$(TOPDIR)/src
MYSQLINC=$(TOPDIR)/mysql/include
CLADLIB=$(TOPDIR)/ClassAdLite/lib
BOSSLIB=$(TOPDIR)/lib
MYSQLLIB=$(TOPDIR)/mysql/lib
PSTREAMINC=$(TOPDIR)/pstream

#RLS stuff
SINC=$(CMSDIR)/lcg/app/releases/SEAL/SEAL_1_3_3/rh73_gcc32/include/
BOOSTINC=$(CMSDIR)/lcg/external/boost/1.30.2/rh73_gcc32/
POOLINC=$(CMSDIR)/lcg/app/releases/POOL/POOL_1_6_1/include/
SEALBASEINC =$(CMSDIR)/lcg/app/releases/SEAL/SEAL_1_3_3/include/
POOLLIB=$(CMSDIR)/lcg/app/releases/POOL/POOL_1_6_1/rh73_gcc32/lib
PLUGINLIB=$(CMSDIR)/lcg/app/releases/SEAL/SEAL_1_3_3/rh73_gcc32/lib/

#Refdb stuff
CURLINC=/usr/include/curl/

EXES = gross
SOURCES = $(wildcard *.cc)
OBJS := $(SOURCES:.cc=.o)
INCLUDES += -I$(CLADINC) -I$(BOSSINC) -I$(MYSQLINC) -I$(POOLINC) -I$(BOOSTINC) -I$(SEALBASEINC) -I$(SINC) -I$(PSTREAMINC) -I$(CURLINC)
LIB_DIRS = -L$(CLADLIB) -L$(BOSSLIB) -L$(MYSQLLIB) -L$(POOLLIB) -L$(PLUGINLIB)
LIB_FILES +=  -lBossComm -lBossBase  -lClassAdLite -lmysqlclient -lz -llcg_FileCatalog -llcg_AttributeList

all: $(EXES)

gross: gross.o $(OBJS)
	$(CPP) $(CPPFLAGS) $(INCLUDES) $(OFLAG) $(BINDIR)/gross gross.o $(OBJS) $(LIB_DIRS) $(LIB_FILES)

gross: gross.cpp $(SOURCES) 

test: test.o $(OBJS)
	$(CPP) $(CPPFLAGS) $(INCLUDES) $(OFLAG) test test.o $(OBJS) $(LIB_DIRS) $(LIB_FILES)

test: test.cpp $(SOURCES)


clean:
	rm -f *.o $(EXES)
depend: 
	makedepend -- $(CPP) $(CPPFLAGS) -- $(INCLUDES) gross.cpp $(SOURCES) $(LIB_DIRS) $(LIB_FILES)

# DO NOT DELETE

gross.o: CommandInterpreter.hh Log.hh Command.hh CommandContainer.hh
gross.o: FileSys.hh /usr/include/sys/stat.h /usr/include/features.h
gross.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
gross.o: /usr/include/bits/types.h
gross.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
gross.o: /usr/include/bits/stat.h /usr/include/sys/unistd.h
gross.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
gross.o: /usr/include/bits/confname.h
BossIf.o: BossIf.hh Log.hh QInfoTask.hh Error.hh Job.hh Task.hh JDL.hh
BossIf.o: LocalDb.hh /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
BossIf.o: /usr/include/sys/types.h /usr/include/features.h
BossIf.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BossIf.o: /usr/include/bits/types.h
BossIf.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
BossIf.o: /usr/include/time.h
BossIf.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
BossIf.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
BossIf.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
BossIf.o: /home/stuartw/boss-v3_4_0_pre1/src/BossCommandInterpreter.h
BossIf.o: /home/stuartw/boss-v3_4_0_pre1/src/BossCommandContainer.h
CladLookup.o: CladLookup.hh Log.hh
CladLookup.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
CladLookup.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
Command.o: Command.hh Log.hh LocalDb.hh
Command.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
Command.o: /usr/include/sys/types.h /usr/include/features.h
Command.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Command.o: /usr/include/bits/types.h
Command.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Command.o: /usr/include/time.h
Command.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
Command.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
Command.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h DbSpec.hh
Command.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
Command.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
Command.o: File.hh
CommandContainer.o: CommandContainer.hh Log.hh Prepare.hh Command.hh
CommandContainer.o: Submit.hh Register.hh Query.hh Output.hh Delete.hh
CommandContainer.o: Kill.hh
CommandInterpreter.o: CommandInterpreter.hh Log.hh Command.hh
CommandInterpreter.o: CommandContainer.hh
ContPrint.o: File.hh Log.hh
DbOrcaGJob.o: DbOrcaGJob.hh Log.hh OrcaGJob.hh Job.hh TaskFactory.hh
DbOrcaGJob.o: Wrapper.hh JDL.hh LocalDb.hh
DbOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
DbOrcaGJob.o: /usr/include/sys/types.h /usr/include/features.h
DbOrcaGJob.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
DbOrcaGJob.o: /usr/include/bits/types.h
DbOrcaGJob.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
DbOrcaGJob.o: /usr/include/time.h
DbOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
DbOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
DbOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
DbOrcaGJob.o: FileSys.hh /usr/include/sys/stat.h /usr/include/bits/stat.h
DbOrcaGJob.o: /usr/include/sys/unistd.h /usr/include/unistd.h
DbOrcaGJob.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
DbOrcaGJob.o: Task.hh File.hh CladLookup.hh
DbOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
DbOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
DbOrcaLocJob.o: DbOrcaLocJob.hh Log.hh OrcaLocJob.hh Job.hh TaskFactory.hh
DbOrcaLocJob.o: Wrapper.hh JDL.hh LocalDb.hh
DbOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
DbOrcaLocJob.o: /usr/include/sys/types.h /usr/include/features.h
DbOrcaLocJob.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
DbOrcaLocJob.o: /usr/include/bits/types.h
DbOrcaLocJob.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
DbOrcaLocJob.o: /usr/include/time.h
DbOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
DbOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
DbOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
DbOrcaLocJob.o: FileSys.hh /usr/include/sys/stat.h /usr/include/bits/stat.h
DbOrcaLocJob.o: /usr/include/sys/unistd.h /usr/include/unistd.h
DbOrcaLocJob.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
DbOrcaLocJob.o: Task.hh File.hh CladLookup.hh
DbOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
DbOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
DbOrcaTask.o: DbOrcaTask.hh Log.hh DbTask.hh Task.hh TaskFactory.hh Job.hh
DbOrcaTask.o: CladLookup.hh /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
DbOrcaTask.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
DbOrcaTask.o: LocalDb.hh /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
DbOrcaTask.o: /usr/include/sys/types.h /usr/include/features.h
DbOrcaTask.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
DbOrcaTask.o: /usr/include/bits/types.h
DbOrcaTask.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
DbOrcaTask.o: /usr/include/time.h
DbOrcaTask.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
DbOrcaTask.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
DbOrcaTask.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
DbSpec.o: DbSpec.hh Log.hh /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
DbSpec.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
DbTask.o: DbTask.hh Log.hh Task.hh Job.hh CladLookup.hh
DbTask.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
DbTask.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
DbTask.o: LocalDb.hh /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
DbTask.o: /usr/include/sys/types.h /usr/include/features.h
DbTask.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
DbTask.o: /usr/include/bits/types.h
DbTask.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
DbTask.o: /usr/include/time.h
DbTask.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
DbTask.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
DbTask.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
Delete.o: Delete.hh Log.hh Command.hh LocalDb.hh
Delete.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
Delete.o: /usr/include/sys/types.h /usr/include/features.h
Delete.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Delete.o: /usr/include/bits/types.h
Delete.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Delete.o: /usr/include/time.h
Delete.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
Delete.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
Delete.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h BossIf.hh
Delete.o: QInfoTask.hh TaskFactory.hh Task.hh
EDGIf.o: EDGIf.hh Log.hh /home/stuartw/boss-v3_4_0_pre1/pstream/pstream.h
EDGIf.o: /usr/include/sys/types.h /usr/include/features.h
EDGIf.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
EDGIf.o: /usr/include/bits/types.h
EDGIf.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
EDGIf.o: /usr/include/time.h /usr/include/sys/wait.h /usr/include/signal.h
EDGIf.o: /usr/include/bits/sigset.h /usr/include/bits/signum.h
EDGIf.o: /usr/include/sys/resource.h /usr/include/bits/resource.h
EDGIf.o: /usr/include/bits/time.h /usr/include/bits/waitflags.h
EDGIf.o: /usr/include/bits/waitstatus.h /usr/include/unistd.h
EDGIf.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
EDGIf.o: StringSpecial.hh
Error.o: Error.hh
File.o: File.hh Log.hh /usr/include/sys/stat.h /usr/include/features.h
File.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
File.o: /usr/include/bits/types.h
File.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
File.o: /usr/include/bits/stat.h
FileSys.o: FileSys.hh Log.hh /usr/include/sys/stat.h /usr/include/features.h
FileSys.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
FileSys.o: /usr/include/bits/types.h
FileSys.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
FileSys.o: /usr/include/bits/stat.h /usr/include/sys/unistd.h
FileSys.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
FileSys.o: /usr/include/bits/confname.h
JDL.o: JDL.hh Log.hh File.hh
Job.o: Job.hh Log.hh File.hh Task.hh Wrapper.hh JDL.hh LocalDb.hh
Job.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
Job.o: /usr/include/sys/types.h /usr/include/features.h
Job.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Job.o: /usr/include/bits/types.h
Job.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Job.o: /usr/include/time.h
Job.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
Job.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
Job.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h DeletePtr.hh
Job.o: ContPrint.hh
Kill.o: Kill.hh Log.hh Command.hh LocalDb.hh
Kill.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
Kill.o: /usr/include/sys/types.h /usr/include/features.h
Kill.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Kill.o: /usr/include/bits/types.h
Kill.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Kill.o: /usr/include/time.h
Kill.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
Kill.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
Kill.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h BossIf.hh
Kill.o: QInfoTask.hh TaskFactory.hh Task.hh
LocalDb.o: LocalDb.hh Log.hh
LocalDb.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
LocalDb.o: /usr/include/sys/types.h /usr/include/features.h
LocalDb.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
LocalDb.o: /usr/include/bits/types.h
LocalDb.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
LocalDb.o: /usr/include/time.h
LocalDb.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
LocalDb.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
LocalDb.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h DbSpec.hh
LocalDb.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
LocalDb.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
Log.o: Log.hh
MySQLDb.o: MySQLDb.hh Log.hh
MySQLDb.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
MySQLDb.o: /usr/include/sys/types.h /usr/include/features.h
MySQLDb.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
MySQLDb.o: /usr/include/bits/types.h
MySQLDb.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
MySQLDb.o: /usr/include/time.h
MySQLDb.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
MySQLDb.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
MySQLDb.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h DbSpec.hh
MySQLDb.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
MySQLDb.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
NewOrcaGJob.o: NewOrcaGJob.hh Log.hh OrcaGJob.hh Job.hh Task.hh
NewOrcaGJob.o: NewOrcaTask.hh NewTask.hh Wrapper.hh JDL.hh LocalDb.hh
NewOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
NewOrcaGJob.o: /usr/include/sys/types.h /usr/include/features.h
NewOrcaGJob.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
NewOrcaGJob.o: /usr/include/bits/types.h
NewOrcaGJob.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
NewOrcaGJob.o: /usr/include/time.h
NewOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
NewOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
NewOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
NewOrcaGJob.o: FileSys.hh /usr/include/sys/stat.h /usr/include/bits/stat.h
NewOrcaGJob.o: /usr/include/sys/unistd.h /usr/include/unistd.h
NewOrcaGJob.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
NewOrcaGJob.o: File.hh CladLookup.hh
NewOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
NewOrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
NewOrcaGJob.o: TaskFactory.hh PhysCat.hh
NewOrcaLocJob.o: NewOrcaLocJob.hh Log.hh OrcaLocJob.hh Job.hh Task.hh
NewOrcaLocJob.o: NewOrcaTask.hh NewTask.hh Wrapper.hh JDL.hh LocalDb.hh
NewOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
NewOrcaLocJob.o: /usr/include/sys/types.h /usr/include/features.h
NewOrcaLocJob.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
NewOrcaLocJob.o: /usr/include/bits/types.h
NewOrcaLocJob.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
NewOrcaLocJob.o: /usr/include/time.h
NewOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
NewOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
NewOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
NewOrcaLocJob.o: FileSys.hh /usr/include/sys/stat.h /usr/include/bits/stat.h
NewOrcaLocJob.o: /usr/include/sys/unistd.h /usr/include/unistd.h
NewOrcaLocJob.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
NewOrcaLocJob.o: File.hh CladLookup.hh
NewOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
NewOrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
NewOrcaLocJob.o: TaskFactory.hh PhysCat.hh
NewOrcaTask.o: NewOrcaTask.hh Log.hh NewTask.hh Task.hh TaskFactory.hh
NewOrcaTask.o: PhysCat.hh Job.hh CladLookup.hh
NewOrcaTask.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
NewOrcaTask.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
NewOrcaTask.o: ContPrint.hh
NewTask.o: NewTask.hh Log.hh Task.hh CladLookup.hh
NewTask.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
NewTask.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
NewTask.o: Job.hh File.hh
OrcaGFactory.o: OrcaGFactory.hh Log.hh TaskFactory.hh NewOrcaTask.hh
OrcaGFactory.o: NewTask.hh Task.hh DbOrcaTask.hh DbTask.hh NewOrcaGJob.hh
OrcaGFactory.o: OrcaGJob.hh Job.hh DbOrcaGJob.hh OrcaJDL.hh JDL.hh
OrcaGFactory.o: OrcaGWrapper.hh Wrapper.hh
OrcaGJob.o: OrcaGJob.hh Log.hh Job.hh Task.hh Wrapper.hh JDL.hh LocalDb.hh
OrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
OrcaGJob.o: /usr/include/sys/types.h /usr/include/features.h
OrcaGJob.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
OrcaGJob.o: /usr/include/bits/types.h
OrcaGJob.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
OrcaGJob.o: /usr/include/time.h
OrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
OrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
OrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
OrcaGJob.o: FileSys.hh /usr/include/sys/stat.h /usr/include/bits/stat.h
OrcaGJob.o: /usr/include/sys/unistd.h /usr/include/unistd.h
OrcaGJob.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
OrcaGJob.o: File.hh CladLookup.hh
OrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
OrcaGJob.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
OrcaGJob.o: ContPrint.hh PhysCat.hh
OrcaGWrapper.o: OrcaGWrapper.hh Log.hh Wrapper.hh CladLookup.hh
OrcaGWrapper.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
OrcaGWrapper.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
OrcaGWrapper.o: OrcaGJob.hh Job.hh File.hh ContPrint.hh
OrcaJDL.o: OrcaJDL.hh Log.hh JDL.hh CladLookup.hh
OrcaJDL.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
OrcaJDL.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
OrcaJDL.o: OrcaGJob.hh Job.hh File.hh
OrcaLocFactory.o: OrcaLocFactory.hh Log.hh TaskFactory.hh NewOrcaTask.hh
OrcaLocFactory.o: NewTask.hh Task.hh DbOrcaTask.hh DbTask.hh NewOrcaLocJob.hh
OrcaLocFactory.o: OrcaLocJob.hh Job.hh DbOrcaLocJob.hh OrcaLocJDL.hh JDL.hh
OrcaLocFactory.o: OrcaLocWrapper.hh Wrapper.hh
OrcaLocJDL.o: OrcaLocJDL.hh Log.hh JDL.hh CladLookup.hh
OrcaLocJDL.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
OrcaLocJDL.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
OrcaLocJDL.o: OrcaLocJob.hh Job.hh File.hh
OrcaLocJob.o: OrcaLocJob.hh Log.hh Job.hh Task.hh Wrapper.hh JDL.hh
OrcaLocJob.o: LocalDb.hh /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
OrcaLocJob.o: /usr/include/sys/types.h /usr/include/features.h
OrcaLocJob.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
OrcaLocJob.o: /usr/include/bits/types.h
OrcaLocJob.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
OrcaLocJob.o: /usr/include/time.h
OrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
OrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
OrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
OrcaLocJob.o: FileSys.hh /usr/include/sys/stat.h /usr/include/bits/stat.h
OrcaLocJob.o: /usr/include/sys/unistd.h /usr/include/unistd.h
OrcaLocJob.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
OrcaLocJob.o: File.hh CladLookup.hh
OrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
OrcaLocJob.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
OrcaLocJob.o: ContPrint.hh PhysCat.hh
OrcaLocWrapper.o: OrcaLocWrapper.hh Log.hh Wrapper.hh CladLookup.hh
OrcaLocWrapper.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
OrcaLocWrapper.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
OrcaLocWrapper.o: OrcaLocJob.hh Job.hh File.hh ContPrint.hh
Output.o: Output.hh Log.hh Command.hh TaskOutput.hh Task.hh FileSys.hh
Output.o: /usr/include/sys/stat.h /usr/include/features.h
Output.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Output.o: /usr/include/bits/types.h
Output.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Output.o: /usr/include/bits/stat.h /usr/include/sys/unistd.h
Output.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
Output.o: /usr/include/bits/confname.h Range.hh TaskFactory.hh
PhysCat.o: PhysCat.hh Log.hh RLSquery.hh
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFileCatalog.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCSystemTools.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCEntry.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeList.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/Attribute.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeTypes.h
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/shared_ptr.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/user.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/select_compiler_config.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/compiler/gcc.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/select_stdlib_config.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/select_platform_config.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/suffix.hpp
PhysCat.o: /usr/include/limits.h /usr/include/features.h
PhysCat.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
PhysCat.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/detail/shared_ptr_nmt.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/assert.hpp
PhysCat.o: /usr/include/assert.h
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/checked_delete.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/throw_exception.hpp
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config.hpp
PhysCat.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/exception
PhysCat.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/detail/atomic_count.hpp
PhysCat.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/new
PhysCat.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/POOLCore/Token.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/POOLCore/Guid.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/Attribute.inl
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeExceptions.h
PhysCat.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealKernel/Exception.h
PhysCat.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealBase/Error.h
PhysCat.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealBase/config.h
PhysCat.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealPlatform/system.h
PhysCat.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/rh73_gcc32/include/SealPlatform/config.h
PhysCat.o: /usr/include/sys/types.h /usr/include/bits/types.h
PhysCat.o: /usr/include/time.h
PhysCat.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealKernel/Status.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeSpecification.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeSpecification.inl
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeListSpecification.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/URIParser.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCException.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFCAction.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFCContainer.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCBuf.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCLeaf.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCImpl.h
PhysCat.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFCContainer.inl
PhysCat.o: File.hh FileSys.hh /usr/include/sys/stat.h
PhysCat.o: /usr/include/bits/stat.h /usr/include/sys/unistd.h
PhysCat.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
PhysCat.o: /usr/include/bits/confname.h TaskFactory.hh RefDBquery.hh
PhysCat.o: /usr/include/curl/curl.h /usr/include/stdio.h /usr/include/libio.h
PhysCat.o: /usr/include/_G_config.h /usr/include/wchar.h
PhysCat.o: /usr/include/bits/wchar.h /usr/include/gconv.h
PhysCat.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
PhysCat.o: /usr/include/bits/stdio_lim.h /usr/include/sys/time.h
PhysCat.o: /usr/include/bits/time.h /usr/include/sys/select.h
PhysCat.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
PhysCat.o: /usr/include/curl/types.h /usr/include/curl/easy.h
Prepare.o: Prepare.hh Log.hh Command.hh TaskFactory.hh Task.hh FileSys.hh
Prepare.o: /usr/include/sys/stat.h /usr/include/features.h
Prepare.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Prepare.o: /usr/include/bits/types.h
Prepare.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Prepare.o: /usr/include/bits/stat.h /usr/include/sys/unistd.h
Prepare.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
Prepare.o: /usr/include/bits/confname.h File.hh
QInfoTask.o: QInfoTask.hh Log.hh Task.hh Job.hh TaskFactory.hh File.hh
QInfoTask.o: BossIf.hh CladLookup.hh
QInfoTask.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
QInfoTask.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
QInfoTask.o: Range.hh ContPrint.hh
Query.o: Query.hh Log.hh Command.hh QInfoTask.hh Task.hh LocalDb.hh
Query.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
Query.o: /usr/include/sys/types.h /usr/include/features.h
Query.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Query.o: /usr/include/bits/types.h
Query.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Query.o: /usr/include/time.h
Query.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
Query.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
Query.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h Range.hh
Query.o: TaskFactory.hh
RLSquery.o: RLSquery.hh
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFileCatalog.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCSystemTools.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCEntry.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeList.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/Attribute.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeTypes.h
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/shared_ptr.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/user.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/select_compiler_config.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/compiler/gcc.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/select_stdlib_config.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/select_platform_config.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/suffix.hpp
RLSquery.o: /usr/include/limits.h /usr/include/features.h
RLSquery.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
RLSquery.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/detail/shared_ptr_nmt.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/assert.hpp
RLSquery.o: /usr/include/assert.h
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/checked_delete.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/throw_exception.hpp
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config.hpp
RLSquery.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/exception
RLSquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/detail/atomic_count.hpp
RLSquery.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/new
RLSquery.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/POOLCore/Token.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/POOLCore/Guid.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/Attribute.inl
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeExceptions.h
RLSquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealKernel/Exception.h
RLSquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealBase/Error.h
RLSquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealBase/config.h
RLSquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealPlatform/system.h
RLSquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/rh73_gcc32/include/SealPlatform/config.h
RLSquery.o: /usr/include/sys/types.h /usr/include/bits/types.h
RLSquery.o: /usr/include/time.h
RLSquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealKernel/Status.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeSpecification.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeSpecification.inl
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeListSpecification.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/URIParser.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCException.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFCAction.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFCContainer.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCBuf.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCLeaf.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCImpl.h
RLSquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFCContainer.inl
RLSquery.o: File.hh Log.hh
Range.o: Range.hh Log.hh Job.hh
RefDBquery.o: RefDBquery.hh RLSquery.hh
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFileCatalog.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCSystemTools.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCEntry.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeList.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/Attribute.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeTypes.h
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/shared_ptr.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/user.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/select_compiler_config.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/compiler/gcc.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/select_stdlib_config.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/select_platform_config.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config/suffix.hpp
RefDBquery.o: /usr/include/limits.h /usr/include/features.h
RefDBquery.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
RefDBquery.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/detail/shared_ptr_nmt.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/assert.hpp
RefDBquery.o: /usr/include/assert.h
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/checked_delete.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/throw_exception.hpp
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/config.hpp
RefDBquery.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/exception
RefDBquery.o: /opt/cms/lcg/external/boost/1.30.2/rh73_gcc32/boost/detail/atomic_count.hpp
RefDBquery.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/new
RefDBquery.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/POOLCore/Token.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/POOLCore/Guid.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/Attribute.inl
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeExceptions.h
RefDBquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealKernel/Exception.h
RefDBquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealBase/Error.h
RefDBquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealBase/config.h
RefDBquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealPlatform/system.h
RefDBquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/rh73_gcc32/include/SealPlatform/config.h
RefDBquery.o: /usr/include/sys/types.h /usr/include/bits/types.h
RefDBquery.o: /usr/include/time.h
RefDBquery.o: /opt/cms/lcg/app/releases/SEAL/SEAL_1_3_3/include/SealKernel/Status.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeSpecification.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeSpecification.inl
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/AttributeList/AttributeListSpecification.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/URIParser.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCException.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFCAction.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFCContainer.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCBuf.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCLeaf.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/FCImpl.h
RefDBquery.o: /opt/cms/lcg/app/releases/POOL/POOL_1_6_1/include/FileCatalog/IFCContainer.inl
RefDBquery.o: File.hh Log.hh /usr/include/curl/curl.h /usr/include/stdio.h
RefDBquery.o: /usr/include/libio.h /usr/include/_G_config.h
RefDBquery.o: /usr/include/wchar.h /usr/include/bits/wchar.h
RefDBquery.o: /usr/include/gconv.h
RefDBquery.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
RefDBquery.o: /usr/include/bits/stdio_lim.h /usr/include/sys/time.h
RefDBquery.o: /usr/include/bits/time.h /usr/include/sys/select.h
RefDBquery.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
RefDBquery.o: /usr/include/curl/types.h /usr/include/curl/easy.h FileSys.hh
RefDBquery.o: /usr/include/sys/stat.h /usr/include/bits/stat.h
RefDBquery.o: /usr/include/sys/unistd.h /usr/include/unistd.h
RefDBquery.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
Register.o: Register.hh Log.hh Command.hh File.hh DbSpec.hh
Register.o: /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
Register.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
Register.o: LocalDb.hh /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
Register.o: /usr/include/sys/types.h /usr/include/features.h
Register.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Register.o: /usr/include/bits/types.h
Register.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Register.o: /usr/include/time.h
Register.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
Register.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
Register.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
StringSpecial.o: StringSpecial.hh
Submit.o: Submit.hh Log.hh Command.hh TaskFactory.hh BossIf.hh QInfoTask.hh
Submit.o: Task.hh FileSys.hh /usr/include/sys/stat.h /usr/include/features.h
Submit.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Submit.o: /usr/include/bits/types.h
Submit.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Submit.o: /usr/include/bits/stat.h /usr/include/sys/unistd.h
Submit.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
Submit.o: /usr/include/bits/confname.h
Task.o: Task.hh Log.hh Job.hh LocalDb.hh
Task.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
Task.o: /usr/include/sys/types.h /usr/include/features.h
Task.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Task.o: /usr/include/bits/types.h
Task.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Task.o: /usr/include/time.h
Task.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
Task.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
Task.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h DeletePtr.hh
Task.o: CladLookup.hh /home/stuartw/boss-v3_4_0_pre1/src/BossClassAd.h
Task.o: /home/stuartw/boss-v3_4_0_pre1/ClassAdLite/include/ClassAdLite.h
Task.o: TaskFactory.hh
TaskFactory.o: TaskFactory.hh Log.hh OrcaGFactory.hh OrcaLocFactory.hh
TaskOutput.o: TaskOutput.hh Log.hh Task.hh Job.hh TaskFactory.hh File.hh
TaskOutput.o: BossIf.hh QInfoTask.hh EDGIf.hh Error.hh LocalDb.hh
TaskOutput.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
TaskOutput.o: /usr/include/sys/types.h /usr/include/features.h
TaskOutput.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
TaskOutput.o: /usr/include/bits/types.h
TaskOutput.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
TaskOutput.o: /usr/include/time.h
TaskOutput.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
TaskOutput.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
TaskOutput.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h
TaskOutput.o: Range.hh
Wrapper.o: Wrapper.hh Log.hh LocalDb.hh
Wrapper.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql.h
Wrapper.o: /usr/include/sys/types.h /usr/include/features.h
Wrapper.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Wrapper.o: /usr/include/bits/types.h
Wrapper.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
Wrapper.o: /usr/include/time.h
Wrapper.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_com.h
Wrapper.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/mysql_version.h
Wrapper.o: /home/stuartw/boss-v3_4_0_pre1/mysql/include/my_alloc.h File.hh
Wrapper.o: DeletePtr.hh
