// /////////////////////////////////////////////////////////////////////
// Program: SirDB
// Version: 1.0
// File:    ClarensBackend.h
// Authors: Jordan Carlson (Caltech), Claudio Grandi (INFN BO)
// Date:    26/09/2004
// Note:
// /////////////////////////////////////////////////////////////////////

#ifndef CLARENS_BACKEND_H
#define CLARENS_BACKEND_H

#include <openssl/rsa.h>
#include <xmlrpc.h>

#include "SirDBBackend.h"
#include "clarens_client.h"

#include "ClarensBackendContact.h"


/***** ClarensBackend *****/

class ClarensBackend : public SirDBBackend {
public:
  /* Use default connection parameters from the BOSS configuration file. */
  ClarensBackend(const std::string& config, const std::string& mode);

  ~ClarensBackend();

  /* Connect to the database (using previously established connection
     parameters). Return 0 on success. */
  int connect();

  /* Disconnect from the database. */
  void disconnect();

  /* Perform a general query, ignoring the results.
     Return 0 on success, negative if an error occurs. */
  int query(const std::string& q);

  /* Perform a SELECT (or similary) query and return the result set.
     If an error occurs, the result set evaluates to false. */
  SirDBResultSet fetch_query(const std::string& q);

  /* Perform a query and return the number of affected rows (for an INSERT-like
     query) or the number of rows in the result set (for a SELECT-like query).
     Return 0 if no rows were affected, negative if an error occurs. */
  int rowcount_query(const std::string& q);

  /* Perform an INSERT or UPDATE query, and return the unique ID generated by
     the AUTO_INCREMENT column.
     Return 0 if no rows are affected, negative if an error occurs. */
  int insert_query(const std::string& q);

  /* Escape the given string so that it can be inserted into the database. */
  std::string escape(std::string s);
  std::string escape(const char* s, size_t len);

  /* Return a string describing the last error encountered by the database.
     Return the empty string if there wasn't an error. */
  std::string errormsg();

private:
  ClarensBackendContact contact_;
  xmlrpc_env env;
  clarens_client* client;
};


class Clarens_ResultSetData : public SirDBResultSetData {
public:
  Clarens_ResultSetData(xmlrpc_value* value);
  ~Clarens_ResultSetData();

  const std::vector<std::vector<char*> >* getrows();
  const std::vector<char*>* getheaders();

private:
  xmlrpc_env env;
  xmlrpc_value* value;
  xmlrpc_value* xvrows;
  xmlrpc_value* xvheaders;
  std::vector<std::vector<char*> > rows;
  std::vector<char*> headers;

  Clarens_ResultSetData();
  bool parsed;
  void parse();
};

#endif // CLARENS_BACKEND_H
