#!/usr/bin/perl

$val{"comment"} = "... STOP";
while ( <STDIN> ) {
  if($_ =~ /.*counter\s+(\d+).*/)  {
      $val{"counter"} = $1;
  }
}
foreach $key (sort keys %val) {
    print "$key=$val{$key}\n";
}

