#!/usr/bin/perl

$|=1;
while ( <STDIN> ) {
  
  if($_ =~ /.*wrapper:CHECKPOINT:\s+(.*)/)  {
      $val = $1;
      print "last_checkpoint = $val\n";
  }
 
  if($_ =~ /.*wrapper:ERROR:\s+(.*)/)  {
      $val = $1;
      print "last_error = $val\n";
  }

  if($_ =~ /.*wrapper:WARNING:\s+(.*)/)  {
      $val = $1;
      print "last_warning = $val\n";
  }
}

